kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-malware-ML
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: malware-ml
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: malware-ml
    spec:
      containers:
      - name: malware-pod
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
