apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: malware-predictor-replicaset
  labels:
    app: malware-predictor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: malware-predictor
  template:
    metadata:
      labels:
        app: malware-predictor
    spec:
      containers:
      - name: malware-predictor
        image: docker.io/draellemeister/mal-predict
        ports:
        - containerPort: 5000