apiVersion: v1
kind: Service
metadata:
  name: nix-builder-service
spec:
  selector:
    app: nix-builder
  ports:
  - protocol: TCP
    port: 22 # External port
    targetPort: 22 # Container port
  type: LoadBalancer # Expose externally

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nix-builder-ssh-keys
data:
  authorized_keys: |
    ssh-rsa AAAAB3... example@example.com

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nix-remote-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nix-builder
  template:
    metadata:
      labels:
        app: nix-builder
    spec:
      initContainers:
      - name: fix-ssh-permissions
        image: busybox
        command: ["sh", "-c", "chmod 600 /root/.ssh/authorized_keys"]
        volumeMounts:
        - name: ssh-keys
          mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
      containers:
      - name: nix-builder
        image: myregistry/nix-builder:latest
        ports:
        - containerPort: 22 # Expose SSH
        volumeMounts:
        - mountPath: /nix/store
          name: nix-store
        - mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
          name: ssh-keys
        command: ["/bin/sh", "-c", "service sshd start && tail -f /dev/null"]
      volumes:
      - name: nix-store
        emptyDir: {}
      - name: ssh-keys
        configMap:
          name: nix-builder-ssh-keys
