apiVersion: apps/v1
kind: Deployment
metadata:
  name: malware-predictor-deployment
  labels:
    app: malware-predictor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: malware-predictor
  template:
    metadata:
      labels:
        app: malware-predictor
    spec:
      containers:
        - name: malware-predictor-container
          image: docker.io/draellemeister/mal-predict:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: malware-predictor-service
  labels:
    app: malware-predictor
spec:
spec:
  selector:
    app: malware-predictor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      #nodePort: 30080  # You can specify a port in the range 30000-32767 or let Kubernetes assign one automatically
  type: NodePort
  