kind: Deployment
apiVersion: apps/v1
metadata:
  name: malware-deploy
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: malware-ml
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: malware-ml
    spec:
      containers:
      - name: malware-pod
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  labels:
    app: malware-ml
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: malware-ml