apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-extraction-deployment
  labels:
    app: feature-extraction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feature-extraction
  template:
    metadata:
      labels:
        app: feature-extraction
    spec:
      containers:
        - name: feature-extraction-container
          image: docker.io/draellemeister/feature-extract
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: feature-extraction-service
  labels:
    app: feature-extraction
spec:
  selector:
    app: feature-extraction
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer