apiVersion: v1
kind: Pod
metadata:
  name: feature-extraction
  labels:
    app: feature-extraction
spec:
  containers:
  - name: feature-extraction
    image: docker.io/draellemeister/feature-extract
    ports:
    - containerPort: 5000